export const blogData = 
[
    {
        "id": "1",
        "title": "How the world came to run on coffee",
        "published_date": "25/02/2022",
        "article": "It’s a rich dark liquid that flows across the world and greases the wheels of our economies. It’s one of the most traded commodities. And there are fears that, with a seemingly irrepressible demand, we may one day run dry. No, I’m not talking about oil, but coffee. More than two billion “cups of joe” are drunk every day and for many, working life would feel impossible without it. As traditionally tea-drinking countries like China are seduced by coffee’s charms, it may soon become the world’s favourite drink. What is driving this insatiable thirst, and how has the beverage come to conquer the world? Is it the abrasive but aromatic flavours, its psychoactive effects or its social currency? And how can its farmers overcome the challenges created by human-made climate change? Coffee’s story starts in the lush highlands of Ethiopia, the natural homeland of the delicate Coffea arabica plant. Although they are called “coffee beans”, the plant is not a legume, and the fruits of the coffee tree look more like cherries when they are first picked. The seeds inside are extracted and dried before the process of roasting turns them into the hard, nutty nodules we feed into our grinders."
    },
    {
        "id": "2",
        "title": "The Culture of Coffee Drinkers",
        "published_date": "15/01/2022",
        "article": "The idea of the morning person aside, morning commuters seem to fall into one of two categories: the Caffeinated and the Un-caffeinated—the latter category being those who intend to consume coffee, but haven't quite gotten their morning java yet. And they're easily recognizable as such. The Caffeinated are bright-eyed and engaged with the day's events already—they're reading their morning papers, or checking email, or reading for pleasure. They're sometimes armed with travel mugs or Ventis from their coffee shop of choice. They rattle the ice in the clear plastic beverage cups from mobile vendors on summer days. They walk a little faster in the early hours having long left last night behind.This is not the case for the Un-Caffeinated. This group sleeps through the AM commute both on the commuter trains and the subway.They're bleary eyed. Materials they intended to review lie unattended in their laps while they linger in the previous night. They walk more slowly up the stairs and are more irritable when you hurry them along—or hurry by them. They stroll, they trudge, they linger."
    },
    {
        "id": "3",
        "title": "The War on Coffee",
        "published_date": "25/12/2021",
        "article": "What would life be without coffee?” King Louis XV of France is said to have asked. “But, then, what is life even with coffee?” he added. Truer, or more apt, words for the present moment were never spoken, now usable as a kind of daily catechism. At a time when coffee remains one of the few things that the anxious sleeper can look forward to in the morning (What is life without it?), giving as it does at least an illusion of recharge and a fresh start, the charge has invariably slipped away by the time the latest grim briefing comes (What is life even with it?). Imagining life without coffee right now is, for many of us, almost impossible, even though the culture of the café that arose in America over the past couple of decades has, for some indefinite period, been shut down.The growth of coffee as a culture, not just as a drink, can be measured in a unit that might be called the Larry, for the peerless comedy writer Larry David. In “Seinfeld,” which he co-created in 1989, coffee came as a normal beverage in a coffee shop—bad, indistinct stuff that might as well have been tea. (Paul Reiser had a nice bit about the codependency of coffee and tea, with tea as coffee’s pathetic friend.) Then, on “Friends,” the characters gathered in a coffee-specific location, Central Perk, but the very invocation of a percolator, the worst way to brew, suggested that they were there more for the company than for the coffee. Six or so Larrys later, by 2020, the plotline of an entire season of David’s own “Curb Your Enthusiasm” turned on a competition between Mocha Joe’s and Latte Larry’s—the “spite store” that Larry opens just to avenge an insult over scones, with many details about a specific kind of Mexican coffee bean he means to steal. The audience was expected to accept as an obvious premise the idea that coffee was a culture of devotion and discrimination, not just a passable caffeinated drink."
    },
    {
        "id": "4",
        "title": "Creating the Perfect Espresso Recipe",
        "published_date": "05/12/2021",
        "article": "Espresso recipes are important in cafés in terms of consistency and flavour. How and why are the espresso recipes made and what are the things you should consider when making a recipe for espresso? Let’s dig deeper into the world of espresso! WHAT TO CHANGE OR MEASURE? There three main things that we want to (at least) measure when making espresso; dose, yield and brew time. Those three measurements you should as a barista check daily and some baristas might even go so crazy that they check those for every espresso that they make. It might be worth mentioning that from here on I will talking only about double espressos. In my opinion you should always make a double and never even touch the single spouted portafilter. But that’s another conversation, let’s concentrate on the recipes this time."
    },
    {
        "id": "5",
        "title": "Trip to Coffee Origin",
        "published_date": "15/11/2021",
        "article": "This year, from May to June, I was in Tanzania, where I volunteered at a coffee farm for two weeks. This was an opportunity offered by World Unite, a volunteer organization that offers opportunities to learn from coffee farmer Dennis. In this blog you can see what I experienced and learned during my trip. The coffee farm where I spent two weeks is located near Kilimanjaro, the highest mountain in Africa and near to the town of Moshi. Agriculture is one of the main sources of livelihood in rural areas and coffee farms. The area and farm I was in were mainly engaged in coffee growing, banana growing and, to a lesser extent, avocados and maize. Children still go to school, but when it's time to harvest, they help their parents. Coffee beans are often dried on beds in Africa. Dennis, a coffee grower with whom I lived and studied for two weeks, is 76 years old and has been involved in coffee on a daily basis for 40 years. Dennis' coffee farm is a fairly traditional small farm in Tanzania - a total of 3 hectares and 200 coffee trees."
    },
    {
        "id": "6",
        "title": "The Best Coffee Cake",
        "published_date": "19/10/2021",
        "article": "Ever wondered how to make the best, moistest coffee cake that will surprise everyone? Look no further. We have this covered. Follow the recipe to successful coffee crumb cake with mocha ribbon and other ways how to use leftover coffee.Want to make the moistest coffee cake for your cafe or your own indulgence? So, I've always wanted to make that special, real coffee taste/smell cake that is really made with lots of good quality coffee, is moist, also crunchy, pleasant and real crowd-pleaser and stays moist for long. And I think, all the essentials are down to this quite simple recipe."
    },
    {
        "id": "7",
        "title": "Want to Brew Better Coffee at Home - Try This!",
        "published_date": "01/10/2021",
        "article": "Everyone wants to drink great coffee always everywhere, right? In cafés you can rely in the barista's expertise and proper equipment but how about better coffee at home also? Have you struggled to brew that delicious coffee at home? Want to know a secret tip which will definitely make your coffee at home taste better? Check out the tip from below! I have always been struggling to brew delicious coffee at home as I'm used to using Mahlkönig EK43 at work and I used to its extremely even grind size. I do have pretty good equipment at home when it comes to filter coffee - Wilfa Uniform grinder, Hario gooseneck kettle, a few Hario v60s, Aeropress, Chemex, the list goes on... But still I have been struggling. The struggle comes from the fact that no non-commercial grinder is able to produce as even grind particle size distribution as Mahlkönig Ek43 or other high end grinders are. So in other words you will have more fines (extremely fine particles) and boulders (extremely big particles) in your coffee dose. I have struggled especially with the fines; my brews have always been kind of muted, lacking brightness and complexity. They have tasted kind of over-extracted even though the extraction levels have been extremely low; my usual brew has been around 1,1% TDS, Extraction Yield 17-19%. Those numbers are the highest I have been able to brew."
    },
    {
        "id": "8",
        "title": "Why the world came to run on coffee",
        "published_date": "16/09/2021",
        "article": "It’s a rich dark liquid that flows across the world and greases the wheels of our economies. It’s one of the most traded commodities. And there are fears that, with a seemingly irrepressible demand, we may one day run dry. No, I’m not talking about oil, but coffee. More than two billion “cups of joe” are drunk every day and for many, working life would feel impossible without it. As traditionally tea-drinking countries like China are seduced by coffee’s charms, it may soon become the world’s favourite drink. What is driving this insatiable thirst, and how has the beverage come to conquer the world? Is it the abrasive but aromatic flavours, its psychoactive effects or its social currency? And how can its farmers overcome the challenges created by human-made climate change? Coffee’s story starts in the lush highlands of Ethiopia, the natural homeland of the delicate Coffea arabica plant. Although they are called “coffee beans”, the plant is not a legume, and the fruits of the coffee tree look more like cherries when they are first picked. The seeds inside are extracted and dried before the process of roasting turns them into the hard, nutty nodules we feed into our grinders."
    },
    {
        "id": "9",
        "title": "The Life of Coffee Drinkers",
        "published_date": "26/08/2021",
        "article": "The idea of the morning person aside, morning commuters seem to fall into one of two categories: the Caffeinated and the Un-caffeinated—the latter category being those who intend to consume coffee, but haven't quite gotten their morning java yet. And they're easily recognizable as such. The Caffeinated are bright-eyed and engaged with the day's events already—they're reading their morning papers, or checking email, or reading for pleasure. They're sometimes armed with travel mugs or Ventis from their coffee shop of choice. They rattle the ice in the clear plastic beverage cups from mobile vendors on summer days. They walk a little faster in the early hours having long left last night behind.This is not the case for the Un-Caffeinated. This group sleeps through the AM commute both on the commuter trains and the subway.They're bleary eyed. Materials they intended to review lie unattended in their laps while they linger in the previous night. They walk more slowly up the stairs and are more irritable when you hurry them along—or hurry by them. They stroll, they trudge, they linger."
    },
    {
        "id": "10",
        "title": "The Battle of Coffee",
        "published_date": "02/08/2021",
        "article": "What would life be without coffee?” King Louis XV of France is said to have asked. “But, then, what is life even with coffee?” he added. Truer, or more apt, words for the present moment were never spoken, now usable as a kind of daily catechism. At a time when coffee remains one of the few things that the anxious sleeper can look forward to in the morning (What is life without it?), giving as it does at least an illusion of recharge and a fresh start, the charge has invariably slipped away by the time the latest grim briefing comes (What is life even with it?). Imagining life without coffee right now is, for many of us, almost impossible, even though the culture of the café that arose in America over the past couple of decades has, for some indefinite period, been shut down.The growth of coffee as a culture, not just as a drink, can be measured in a unit that might be called the Larry, for the peerless comedy writer Larry David. In “Seinfeld,” which he co-created in 1989, coffee came as a normal beverage in a coffee shop—bad, indistinct stuff that might as well have been tea. (Paul Reiser had a nice bit about the codependency of coffee and tea, with tea as coffee’s pathetic friend.) Then, on “Friends,” the characters gathered in a coffee-specific location, Central Perk, but the very invocation of a percolator, the worst way to brew, suggested that they were there more for the company than for the coffee. Six or so Larrys later, by 2020, the plotline of an entire season of David’s own “Curb Your Enthusiasm” turned on a competition between Mocha Joe’s and Latte Larry’s—the “spite store” that Larry opens just to avenge an insult over scones, with many details about a specific kind of Mexican coffee bean he means to steal. The audience was expected to accept as an obvious premise the idea that coffee was a culture of devotion and discrimination, not just a passable caffeinated drink."
    },
    {
        "id": "11",
        "title": "Creating the Perfect Latte Recipe",
        "published_date": "20/07/2021",
        "article": "Espresso recipes are important in cafés in terms of consistency and flavour. How and why are the espresso recipes made and what are the things you should consider when making a recipe for espresso? Let’s dig deeper into the world of espresso! WHAT TO CHANGE OR MEASURE? There three main things that we want to (at least) measure when making espresso; dose, yield and brew time. Those three measurements you should as a barista check daily and some baristas might even go so crazy that they check those for every espresso that they make. It might be worth mentioning that from here on I will talking only about double espressos. In my opinion you should always make a double and never even touch the single spouted portafilter. But that’s another conversation, let’s concentrate on the recipes this time."
    },
    {
        "id": "12",
        "title": "How is Tanzanian Coffee?",
        "published_date": "07/07/2021",
        "article": "This year, from May to June, I was in Tanzania, where I volunteered at a coffee farm for two weeks. This was an opportunity offered by World Unite, a volunteer organization that offers opportunities to learn from coffee farmer Dennis. In this blog you can see what I experienced and learned during my trip. The coffee farm where I spent two weeks is located near Kilimanjaro, the highest mountain in Africa and near to the town of Moshi. Agriculture is one of the main sources of livelihood in rural areas and coffee farms. The area and farm I was in were mainly engaged in coffee growing, banana growing and, to a lesser extent, avocados and maize. Children still go to school, but when it's time to harvest, they help their parents. Coffee beans are often dried on beds in Africa. Dennis, a coffee grower with whom I lived and studied for two weeks, is 76 years old and has been involved in coffee on a daily basis for 40 years. Dennis' coffee farm is a fairly traditional small farm in Tanzania - a total of 3 hectares and 200 coffee trees."
    },
    {
        "id": "13",
        "title": "The Best Coffee Cookie",
        "published_date": "26/06/2021",
        "article": "Ever wondered how to make the best, moistest coffee cake that will surprise everyone? Look no further. We have this covered. Follow the recipe to successful coffee crumb cake with mocha ribbon and other ways how to use leftover coffee.Want to make the moistest coffee cake for your cafe or your own indulgence? So, I've always wanted to make that special, real coffee taste/smell cake that is really made with lots of good quality coffee, is moist, also crunchy, pleasant and real crowd-pleaser and stays moist for long. And I think, all the essentials are down to this quite simple recipe."
    },
    {
        "id": "14",
        "title": "Want to Brew Better Coffee at Office - You cant!",
        "published_date": "20/05/2021",
        "article": "Everyone wants to drink great coffee always everywhere, right? In cafés you can rely in the barista's expertise and proper equipment but how about better coffee at home also? Have you struggled to brew that delicious coffee at home? Want to know a secret tip which will definitely make your coffee at home taste better? Check out the tip from below! I have always been struggling to brew delicious coffee at home as I'm used to using Mahlkönig EK43 at work and I used to its extremely even grind size. I do have pretty good equipment at home when it comes to filter coffee - Wilfa Uniform grinder, Hario gooseneck kettle, a few Hario v60s, Aeropress, Chemex, the list goes on... But still I have been struggling. The struggle comes from the fact that no non-commercial grinder is able to produce as even grind particle size distribution as Mahlkönig Ek43 or other high end grinders are. So in other words you will have more fines (extremely fine particles) and boulders (extremely big particles) in your coffee dose. I have struggled especially with the fines; my brews have always been kind of muted, lacking brightness and complexity. They have tasted kind of over-extracted even though the extraction levels have been extremely low; my usual brew has been around 1,1% TDS, Extraction Yield 17-19%. Those numbers are the highest I have been able to brew."
    },
    {
        "id": "15",
        "title": "The Coffee Drinkers",
        "published_date": "11/04/2021",
        "article": "The idea of the morning person aside, morning commuters seem to fall into one of two categories: the Caffeinated and the Un-caffeinated—the latter category being those who intend to consume coffee, but haven't quite gotten their morning java yet. And they're easily recognizable as such. The Caffeinated are bright-eyed and engaged with the day's events already—they're reading their morning papers, or checking email, or reading for pleasure. They're sometimes armed with travel mugs or Ventis from their coffee shop of choice. They rattle the ice in the clear plastic beverage cups from mobile vendors on summer days. They walk a little faster in the early hours having long left last night behind.This is not the case for the Un-Caffeinated. This group sleeps through the AM commute both on the commuter trains and the subway.They're bleary eyed. Materials they intended to review lie unattended in their laps while they linger in the previous night. They walk more slowly up the stairs and are more irritable when you hurry them along—or hurry by them. They stroll, they trudge, they linger."
    }
];

 